----------------------------------TẠO DATABASE----------------------------------
CREATE DATABASE QLTHUVIEN
GO
USE QLTHUVIEN
GO
----------------------------------TẠO CÁC TABLE----------------------------------
SET DATEFORMAT DMY
CREATE TABLE GIOITINH
(
	GIOITINH NVARCHAR(4) PRIMARY KEY NOT NULL
)
GO
CREATE TABLE	 TACGIA
(
	TENTACGIA NVARCHAR(50) PRIMARY KEY NOT NULL
)
GO
CREATE TABLE	 NHAXUATBAN
(
	TENNXB NVARCHAR(50) PRIMARY KEY NOT NULL,
	SODT VARCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	EMAIL VARCHAR(50) NULL,
	WEBSITE VARCHAR(50) NULL
)
GO
CREATE TABLE	 THELOAI
(
	TENTHELOAI NVARCHAR(50) PRIMARY KEY NOT NULL
)
GO
CREATE TABLE	 SACH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	TENSACH NVARCHAR(50) NOT NULL,
	TENNXB NVARCHAR(50) NOT NULL,
	TENTHELOAI NVARCHAR(50) NOT NULL,
	TENTACGIA NVARCHAR(50) NOT NULL,
	SOLUONGTON INT NOT NULL,
	SOLUONGMUON INT NOT NULL
)
GO
CREATE TABLE	 DOCGIA
(
	IDMASOTHE INT IDENTITY(2001,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	GIOITINH NVARCHAR(4) NULL,
	NGAYSINH DATE NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	DIACHI NVARCHAR(50) NULL,
	NGAYLAP DATE NULL,
	HANSUDUNG DATE NULL
)
GO

CREATE TABLE TAIKHOAN
(
	USERNAME NVARCHAR(50) PRIMARY KEY NOT NULL,
	MATKHAU NVARCHAR(50) NOT NULL,
	HOTEN NVARCHAR(50) NOT NULL,
	QUYEN NVARCHAR(50)
)
GO
CREATE TABLE	 NHANVIEN
(
	ID INT IDENTITY(101,1) PRIMARY KEY,
	HOTEN NVARCHAR(50) NOT NULL,
	USERNAME NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NULL,
	GIOITINH NVARCHAR(4) NULL,
	SODT NCHAR(20) NULL,
	CMND NCHAR(20) NULL,
	NGAYVAOLAM DATE NULL,
	CONSTRAINT FK_USERNAMENHANVIEN FOREIGN KEY (USERNAME) REFERENCES TAIKHOAN(USERNAME)
)
GO
CREATE TABLE PHIEUMUON
(
	ID INT IDENTITY(1000,1) PRIMARY KEY,
	IDMATHEDOCGIA INT NOT NULL,
	TENDOCGIA NVARCHAR(50) NOT NULL,
	IDTHUTHU INT NOT NULL,
	HOTENTHUTHU NVARCHAR(50) NOT NULL,
	NGAYMUON DATE NOT NULL,
	NGAYTRA DATE NOT NULL,
	CONSTRAINT FK_THUTHU FOREIGN KEY (IDTHUTHU) REFERENCES NHANVIEN(ID),
	CONSTRAINT FK_DOCGIA FOREIGN KEY (IDMATHEDOCGIA) REFERENCES DOCGIA(IDMASOTHE)
)

GO
CREATE TABLE CHITIETPHIEUMUON
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDSACH INT NOT NULL,
	TENSACH NVARCHAR(50) NOT NULL,
	IDPHIEUMUON INT NOT NULL,
	CONSTRAINT FK_PHIEUMUON FOREIGN KEY (IDPHIEUMUON) REFERENCES PHIEUMUON(ID)
)

GO
CREATE TABLE	 PHIEUTRA
(
	IDPHIEU INT IDENTITY(1,1) PRIMARY KEY,
	IDDOCGIA INT NOT NULL,
	TENDOCGIA NVARCHAR(50) NOT NULL,
	IDTHUTHU INT NOT NULL,
	HOTENTHUTHU NVARCHAR(50) NOT NULL,
	NGAYLAPPHIEU DATE NOT NULL,
	SONGAYQUAHAN INT NOT NULL,
	TIENPHAT FLOAT NOT NULL,
	CONSTRAINT FK_PPTHUTHU FOREIGN KEY (IDTHUTHU) REFERENCES NHANVIEN(ID),
	CONSTRAINT FK_PPDOCGIA FOREIGN KEY (IDDOCGIA) REFERENCES DOCGIA(IDMASOTHE)
)

INSERT INTO GIOITINH VALUES
(N'Nam'), (N'Nữ')

INSERT INTO TAIKHOAN VALUES
('admin', 'admin', N'Nguyễn Văn Admin','admin'),
('a', 'a', N'Nguyễn Văn A','user'),
('b', 'b', N'Nguyễn Văn B','user'),
('c', 'c', N'Nguyễn Văn C','user')

INSERT INTO NHANVIEN OUTPUT inserted.ID VALUES
(N'Nguyễn Văn A', 'a', '14/3/2003', N'Nam', '012345678', '876543210', '15/7/2015'),
(N'Nguyễn Văn B', 'b', '3/8/1990', N'Nam', '019821678', '53512210', '20/9/2020'),
(N'Nguyễn Thị Quỳnh C', 'c', '8/5/1995', N'Nữ', '088342678', '68644320', '4/3/2017')

INSERT INTO TACGIA VALUES
(N'Nguyễn Nhật Ánh'),
(N'Ngô Sĩ Liên')

INSERT INTO NHAXUATBAN VALUES
(N'NXB Kim Đồng', '01900571595', N'Số 55 Quang Trung, Nguyễn Du, Hai Bà Trưng, Hà Nội', 'cskh_online@nxbkimdong.com.vn', 'nxbkimdong.com.vn'),
(N'NXB Giáo dục Việt Nam', '02438220801', N'Số 81 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội', '', 'www.nxbgd.vn')

INSERT INTO THELOAI VALUES
(N'Tiểu thuyết'),
(N'Truyện cười'),
(N'Lịch sử')

INSERT INTO SACH OUTPUT inserted.ID VALUES
(N'Cho tôi xin một vé đi tuổi thơ', N'NXB Kim Đồng', N'Tiểu thuyết', N'Nguyễn Nhật Ánh', 200, 0),
(N'Đại Việt sử ký toàn thư', N'NXB Giáo dục Việt Nam', N'Lịch Sử', N'Ngô Sĩ Liên', 100, 0)

SET DATEFORMAT DMY
INSERT INTO DOCGIA OUTPUT inserted.IDMASOTHE VALUES
(N'Trần Văn B', N'Nam', '5/3/1986', '0123456789', '829582192', N'Số 15 Lê Trọng Tấn, Tây Thạnh, Tân Phú, TP.HCM', '15/5/2022', '15/5/2023'),
(N'Lý Thị Trâm', N'Nữ', '5/3/2003', '0123456789', '829582192', N'Số 14 Lê Thúc Hoạch, Phú Thọ Hoà, Tân Phú, TP.HCM', '17/5/2022', '17/5/2023'),
(N'Nguyễn Hoàng Phương Nam', N'Nam', '5/3/2005', '0123456789', '829582192', N'Hẻm 150/21/23 Đường 26 Tháng 3, Bình Hưng Hoà, Bình Tân, TP.HCM', '1/4/2022', '1/4/2023'),
(N'Nguyễn Ngọc Thảo Nhi', N'Nữ', '5/3/1999', '0123456789', '829582192', N'Số 343D Lạc Long Quân, Phường 5, Quận 11, TP.HCM', '5/6/2021', '5/6/2022')